services:
  lead_backend_dev:
    container_name: lead-backend-dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: >
      bash -c "
        python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app/
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      - lead_redis_dev
      - lead_db_dev
    networks:
      - lead_network_dev


  lead_db_dev:
    image: postgis/postgis:15-3.3
    container_name: lead-db-dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5433:5432
    networks:
      - lead_network_dev


  lead_redis_dev:
    image: "redis:alpine"
    container_name: lead-redis-dev
    privileged: true
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    env_file:
      - .env
    networks:
      - lead_network_dev


  lead_celery_worker_dev:
    container_name: lead-celery-worker-dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env
    command: celery -A core.celery worker --loglevel DEBUG -P threads
    depends_on:
      - lead_redis_dev
    networks:
      - lead_network_dev


  lead_celery_beat_dev:
    container_name: lead-celery-beat-dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env
    command: celery -A core.celery beat --pidfile= --loglevel DEBUG
    depends_on:
      - lead_redis_dev
    networks:
      - lead_network_dev


volumes:
  postgres_data_dev:
networks:
  lead_network_dev:
